services:
  mariadb:
    build: requirements/mariadb
    container_name: mariadb
    environment:
      - DB_ADMIN_USERNAME=${DB_ADMIN_USERNAME}
      - DB_ADMIN_HOST=${DB_ADMIN_HOST}
      - DB_ADMIN_PASSWORD=${DB_ADMIN_PASSWORD}
      - DB_USERNAME=${DB_USERNAME}
      - DB_HOST=${DB_HOST}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
    expose:
      - 3306
    networks:
      - inception
    restart: always
    volumes:
      - mariadb_volume:/var/lib/mysql
  wordpress:
    build: requirements/wordpress
    container_name: wordpress
    environment:
      - DB_NAME=${DB_NAME}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - WP_ADMIN_USERNAME=${WP_ADMIN_USERNAME}
      - WP_ADMIN_PASSWORD=${WP_ADMIN_PASSWORD}
      - WP_ADMIN_EMAIL=${WP_ADMIN_EMAIL}
    expose:
      - 9000
    networks:
      - inception
    volumes:
      - wordpress_volume:/var/www/html
  nginx:
    build: requirements/nginx
    container_name: nginx
    networks:
      - inception
    volumes:
      - wordpress_volume:/var/www/html
    ports:
      - 443:443 #https
      - 80:80   #http

volumes:
  mariadb_volume:
    driver: local
    driver_opts:
      device: /home/aautin/data/mysql
      o: bind
      type: none
  wordpress_volume:
    driver: local
    driver_opts:
      device: /home/aautin/data/wordpress
      o: bind
      type: none

networks:
  inception:
