services:
  mariadb:
    build: requirements/mariadb
    container_name: mariadb
    environment:
      - ADMIN_USERNAME=${ADMIN_USERNAME}
      - ADMIN_HOST=${ADMIN_HOST}
      - ADMIN_PASSWORD=${ADMIN_PASSWORD}
      - WP_USERNAME=${WP_USERNAME}
      - WP_HOST=${WP_HOST}
      - WP_PASSWORD=${WP_PASSWORD}
      - DB_NAME=${DB_NAME}
    expose:
      - 3306
    networks:
      - inception
    restart: always
    volumes:
      - mariadb_volume:/var/lib/mysql
  wordpress:
    build: requirements/wordpress
    container_name: wordpress
    environment:
      - DB_NAME=${DB_NAME}
      - WP_USERNAME=${WP_USERNAME}
      - WP_PASSWORD=${WP_PASSWORD}
    expose:
      - 9000
    networks:
      - inception

volumes:
  mariadb_volume:
    driver: local
    driver_opts:
      device: /home/aautin/data/mysql
      o: bind
      type: none

networks:
  inception:
